SENSE_ANNOTATED_PREPPED_TRAINING_DATA=/ultratree/language-model/tiny.sqlite
SENSE_ANNOTATED_PREPPED_HELD_OUT_DATA=/ultratree/language-model/validation.sqlite
COMPRESSED_SENSE_ANNOTATED_TRAINING_DATA=ultratree-sense-annotated-training-data.sql.gz
COMPRESSED_SENSE_ANNOTATED_TRAINING_DECODINGS=ultratree-sense-annotated-training-decode.sql.gz
COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DATA=ultratree-sense-annotated-heldout-data.sql.gz
COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DECODINGS=ultratree-sense-annotated-training-heldout.sql.gz

.PHONY: all

all: $(COMPRESSED_SENSE_ANNOTATED_TRAINING_DATA) $(COMPRESSED_SENSE_ANNOTATED_TRAINING_DECODINGS) $(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DATA) $(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DECODINGS)
	echo Done


$(COMPRESSED_SENSE_ANNOTATED_TRAINING_DATA): $(SENSE_ANNOTATED_PREPPED_TRAINING_DATA)
	sqlite3 $(SENSE_ANNOTATED_PREPPED_TRAINING_DATA) ".dump training_data" > .csatd.sqlite
	gzip -9 .csatd.sqlite
	mv .csatd.sqlite.gz $(COMPRESSED_SENSE_ANNOTATED_TRAINING_DATA)

$(COMPRESSED_SENSE_ANNOTATED_TRAINING_DECODINGS): $(SENSE_ANNOTATED_PREPPED_TRAINING_DATA)
	sqlite3 $(SENSE_ANNOTATED_PREPPED_TRAINING_DATA) ".dump decodings" > .csatc.sqlite
	gzip -9 .csatc.sqlite
	mv .csatc.sqlite.gz $(COMPRESSED_SENSE_ANNOTATED_TRAINING_DECODINGS)



$(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DATA): $(SENSE_ANNOTATED_PREPPED_HELD_OUT_DATA)
	sqlite3 $(SENSE_ANNOTATED_PREPPED_HELD_OUT_DATA) ".dump training_data" > .csahod.sqlite
	gzip -9 .csahod.sqlite
	mv .csahod.sqlite.gz $(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DATA)

$(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DECODINGS): $(SENSE_ANNOTATED_PREPPED_HELD_OUT_DATA)
	sqlite3 $(SENSE_ANNOTATED_PREPPED_HELD_OUT_DATA) ".dump decodings" > .csahoc.sqlite
	gzip -9 .csahoc.sqlite
	mv .csahoc.sqlite.gz $(COMPRESSED_SENSE_ANNOTATED_HELD_OUT_DECODINGS)
